#!/bin/bash

set -o errexit

HOSTNAME="`ec2metadata --instance-id`.test.ci.koding.io"

export HOME=/root/
export REPOSITORY_PATH='/opt/koding'

export CI="true"
export WERCKER="true"

export CONFIG_DEBUGMODE="true"

ulimit -n 10240

cd $REPOSITORY_PATH

git config user.email 'sysops@koding.com'
git config user.name 'Koding Bot'

pip install docker-compose

docker-compose -f docker-compose-init.yml run init configure \
               --config dev --host $HOSTNAME \
               --hostname $HOSTNAME --publicPort 80 \
               --disable-segment

docker-compose up -d

exit 0
